export type PeptideSource = { label: string; url: string };

export type PeptideEntry = {
  name: string;
  aka?: string;
  category: PeptideCategory;
  researched: string;
  /** Molecular profile */
  molecularFormula?: string;
  molecularWeight?: string;
  sequence?: string;
  compoundClass?: string;
  halfLife?: string;
  target?: string;
  /** What it is used for, in research contexts */
  uses?: string[];
  mechanism?: string;
  sources?: PeptideSource[];
};

export const PEPTIDE_CATEGORIES = [
  "Healing & Recovery",
  "Growth Hormone",
  "Metabolic & GLP-1",
  "Muscle & Anabolic",
  "Cognitive & Neuro",
  "Immune",
  "Longevity & Sleep",
  "Cosmetic & Sexual Health",
  "Hormonal",
  "Other Research Compounds",
] as const;

export type PeptideCategory = (typeof PEPTIDE_CATEGORIES)[number];

const pubmed = (id: string, label: string): PeptideSource => ({
  label,
  url: `https://pubmed.ncbi.nlm.nih.gov/${id}/`,
});

export const PEPTIDE_LIBRARY: PeptideEntry[] = [
  {
    name: "BPC-157",
    aka: "Body Protection Compound 157, PL 14736",
    category: "Healing & Recovery",
    researched: "Researched for gut lining repair, tendon/ligament healing, and systemic anti-inflammatory effects.",
    molecularFormula: "C62H98N16O22",
    molecularWeight: "1419.5 g/mol",
    sequence: "Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val",
    compoundClass: "Synthetic pentadecapeptide (partial sequence of human gastric juice protein BPC)",
    halfLife: "~4 hours (subcutaneous, animal models)",
    target: "VEGFR2 / nitric oxide and growth-factor signaling",
    uses: [
      "Tendon, ligament and muscle injury models",
      "Gastrointestinal mucosal integrity and ulcer models",
      "Angiogenesis and wound closure",
      "NSAID-induced tissue damage protection",
    ],
    mechanism:
      "Upregulates VEGFR2 and the nitric oxide system, promoting angiogenesis and fibroblast migration at injury sites while modulating inflammatory cytokines.",
    sources: [
      pubmed("29863456", "Chang et al. — BPC-157 and tendon fibroblast outgrowth"),
      pubmed("30915550", "Sikiric et al. — Stable gastric pentadecapeptide BPC-157 review"),
    ],
  },
  {
    name: "TB-500",
    aka: "Thymosin Beta-4 fragment",
    category: "Healing & Recovery",
    researched: "Researched for soft-tissue recovery, muscle repair, and improved cellular migration.",
    molecularFormula: "C33H55N9O12",
    molecularWeight: "889.0 g/mol (Ac-LKKTETQ fragment)",
    sequence: "Ac-Leu-Lys-Lys-Thr-Glu-Thr-Gln",
    compoundClass: "Synthetic fragment of the actin-binding protein Thymosin Beta-4",
    halfLife: "~2–3 hours (parent Tβ4 longer in circulation)",
    target: "G-actin sequestration / actin cytoskeleton",
    uses: ["Muscle and tendon repair models", "Cardiac tissue repair research", "Corneal and dermal wound healing", "Cell migration and angiogenesis studies"],
    mechanism:
      "Binds G-actin and regulates actin polymerization, enabling cell migration, endothelial differentiation and new blood-vessel formation in injured tissue.",
    sources: [
      pubmed("22348196", "Goldstein & Kleinman — Thymosin β4 in tissue repair"),
      pubmed("20955691", "Crockford et al. — Thymosin β4 clinical potential"),
    ],
  },
  {
    name: "KPV",
    category: "Healing & Recovery",
    researched: "Researched for anti-inflammatory effects, skin healing, and immune modulation.",
    molecularFormula: "C19H26N6O4",
    molecularWeight: "402.4 g/mol",
    sequence: "Lys-Pro-Val",
    compoundClass: "C-terminal tripeptide of alpha-MSH",
    halfLife: "Short (minutes to ~1 hour)",
    target: "NF-κB signaling / melanocortin pathway",
    uses: ["Colitis and IBD models", "Dermatitis and skin repair", "Anti-inflammatory cytokine research"],
    mechanism: "Suppresses NF-κB and pro-inflammatory cytokine transcription without the pigmentation effects of full-length alpha-MSH.",
    sources: [pubmed("18845615", "Dalmasso et al. — KPV and intestinal inflammation")],
  },
  {
    name: "LL-37",
    category: "Immune",
    researched: "Researched for antimicrobial activity, immune response, and tissue repair signaling.",
    molecularFormula: "C205H340N60O53",
    molecularWeight: "4493.3 g/mol",
    sequence: "LLGDFFRKSKEKIGKEFKRIVQRIKDFLRNLVPRTES",
    compoundClass: "Human cathelicidin antimicrobial peptide",
    halfLife: "Short in plasma; longer at tissue sites",
    target: "Bacterial membranes, FPRL1 receptor",
    uses: ["Antimicrobial and biofilm research", "Wound healing", "Innate immune signaling"],
    mechanism: "Disrupts microbial membranes and acts as a chemoattractant that recruits immune cells and promotes re-epithelialization.",
    sources: [pubmed("22069395", "Vandamme et al. — LL-37 immunomodulatory review")],
  },
  {
    name: "CJC-1295 (with DAC)",
    category: "Growth Hormone",
    researched: "Researched as a long-acting GHRH analog to elevate baseline growth hormone and IGF-1.",
    molecularFormula: "C165H269N47O46",
    molecularWeight: "3647.2 g/mol",
    sequence: "Tyr-D-Ala-Asp-Ala-Ile-Phe-Thr-Gln-Ser-Tyr-Arg-Lys-Val-Leu-Ala-Gln-Leu-Ser-Ala-Arg-Lys-Leu-Leu-Gln-Asp-Ile-Leu-Ser-Arg-(Lys-DAC)",
    compoundClass: "GHRH (1-29) analog with Drug Affinity Complex",
    halfLife: "~6–8 days",
    target: "GHRH receptor (pituitary somatotrophs)",
    uses: ["Sustained GH/IGF-1 elevation studies", "Body composition research", "Sleep and recovery research"],
    mechanism: "Binds albumin via its DAC linker for extended circulation, providing continuous GHRH-receptor stimulation and raised baseline GH pulses.",
    sources: [pubmed("16352683", "Teichman et al. — CJC-1295 sustained GH/IGF-1 elevation")],
  },
  {
    name: "Ipamorelin",
    category: "Growth Hormone",
    researched: "Researched as a selective GH secretagogue that boosts growth hormone without spiking cortisol or prolactin.",
    molecularFormula: "C38H49N9O5",
    molecularWeight: "711.9 g/mol",
    sequence: "Aib-His-D-2-Nal-D-Phe-Lys-NH2",
    compoundClass: "Pentapeptide ghrelin-receptor (GHS-R1a) agonist",
    halfLife: "~2 hours",
    target: "GHS-R1a (ghrelin receptor)",
    uses: ["Selective GH pulse research", "Recovery and lean-mass studies", "Gastric motility research"],
    mechanism: "Selectively activates the ghrelin receptor to trigger GH release with minimal effect on ACTH, cortisol or prolactin.",
    sources: [pubmed("9849822", "Raun et al. — Ipamorelin, the first selective GH secretagogue")],
  },
  {
    name: "Sermorelin",
    category: "Growth Hormone",
    researched: "Researched for stimulating natural GH release, sleep quality, and recovery.",
    molecularFormula: "C149H246N44O42S",
    molecularWeight: "3357.9 g/mol",
    sequence: "GHRH (1-29) amide",
    compoundClass: "GHRH analog",
    halfLife: "~10–20 minutes",
    target: "GHRH receptor",
    uses: ["GH-deficiency diagnostics", "Sleep architecture research", "Age-related GH decline studies"],
    mechanism: "Mimics endogenous GHRH, stimulating pulsatile pituitary GH secretion that remains under normal negative feedback.",
    sources: [pubmed("9849822", "GH secretagogue background literature")],
  },
  {
    name: "Tesamorelin",
    category: "Growth Hormone",
    researched: "Researched for reducing visceral adipose tissue and improving lipid metabolism.",
    molecularFormula: "C221H366N72O67S",
    molecularWeight: "5135.9 g/mol",
    sequence: "trans-3-hexenoyl-GHRH(1-44) amide",
    compoundClass: "Stabilized GHRH analog",
    halfLife: "~26–38 minutes",
    target: "GHRH receptor",
    uses: ["Visceral adipose tissue reduction", "Lipodystrophy research", "Triglyceride and liver fat studies"],
    mechanism: "Extended-stability GHRH analog that increases endogenous GH and IGF-1, preferentially mobilizing visceral fat stores.",
    sources: [pubmed("21030489", "Falutz et al. — Tesamorelin and visceral fat")],
  },
  {
    name: "Hexarelin",
    category: "Growth Hormone",
    researched: "Researched as a potent GH secretagogue for growth hormone release and cardiac protection.",
    molecularFormula: "C47H58N12O6",
    molecularWeight: "887.0 g/mol",
    sequence: "His-D-2-methyl-Trp-Ala-Trp-D-Phe-Lys-NH2",
    compoundClass: "Hexapeptide GHS-R agonist",
    halfLife: "~55 minutes",
    target: "GHS-R1a and CD36",
    uses: ["Potent GH release studies", "Cardioprotection research"],
    mechanism: "Strong ghrelin-receptor agonism with additional CD36-mediated cardiac effects; tachyphylaxis is observed with continuous dosing.",
    sources: [pubmed("11549679", "Broglio et al. — Hexarelin cardiovascular actions")],
  },
  {
    name: "GHRP-2",
    category: "Growth Hormone",
    researched: "Researched for growth hormone release, appetite stimulation, and recovery.",
    molecularFormula: "C45H55N9O6",
    molecularWeight: "817.9 g/mol",
    sequence: "D-Ala-D-2-Nal-Ala-Trp-D-Phe-Lys-NH2",
    compoundClass: "Growth hormone releasing peptide",
    halfLife: "~30 minutes",
    target: "GHS-R1a",
    uses: ["GH secretion studies", "Appetite and energy-balance research"],
    mechanism: "Ghrelin-mimetic that amplifies GH pulse amplitude; mild ACTH/cortisol and prolactin elevation reported.",
  },
  {
    name: "GHRP-6",
    category: "Growth Hormone",
    researched: "Researched for growth hormone release, appetite increase, and tissue repair.",
    molecularFormula: "C46H56N12O6",
    molecularWeight: "873.0 g/mol",
    sequence: "His-D-Trp-Ala-Trp-D-Phe-Lys-NH2",
    compoundClass: "Growth hormone releasing peptide",
    halfLife: "~15–60 minutes",
    target: "GHS-R1a",
    uses: ["GH secretion research", "Strong appetite stimulation models", "Gastric and cardiac tissue protection"],
    mechanism: "Potent ghrelin-receptor agonist with pronounced hunger signaling alongside GH release.",
  },
  {
    name: "Ipamorelin + CJC-1295 (combo)",
    category: "Growth Hormone",
    researched: "Researched for synergistic GH release, recovery, and body composition.",
    compoundClass: "GHRH analog + selective GHS-R agonist stack",
    target: "GHRH receptor + GHS-R1a",
    uses: ["Synergistic GH pulse research", "Recovery and sleep protocols"],
    mechanism:
      "Combines a GHRH analog (raises pulse baseline) with a ghrelin-receptor agonist (raises pulse amplitude), producing a larger GH release than either alone.",
  },
  {
    name: "HGH Fragment 176-191",
    category: "Metabolic & GLP-1",
    researched: "Researched for fat oxidation, lipolysis, and metabolic enhancement.",
    molecularFormula: "C78H125N23O23S2",
    molecularWeight: "1817.1 g/mol",
    sequence: "C-terminal fragment (176-191) of human growth hormone",
    compoundClass: "GH fragment / lipolytic peptide",
    halfLife: "~30 minutes",
    target: "Beta-3 adrenergic receptor pathway (adipocytes)",
    uses: ["Lipolysis research", "Obesity models without glucose disruption"],
    mechanism: "Reproduces the lipolytic region of growth hormone while avoiding the receptor interactions responsible for insulin resistance.",
    sources: [pubmed("11713213", "Heffernan et al. — GH fragment and fat metabolism")],
  },
  {
    name: "AOD-9604",
    category: "Metabolic & GLP-1",
    researched: "Researched for fat metabolism, lipolysis, and weight management without hunger modulation.",
    molecularFormula: "C78H123N23O23S2",
    molecularWeight: "1815.1 g/mol",
    sequence: "Tyr-hGH(177-191)",
    compoundClass: "Modified GH fragment",
    halfLife: "~30 minutes",
    target: "Adipocyte lipolytic pathways",
    uses: ["Body-fat reduction models", "Cartilage repair research"],
    mechanism: "Stimulates lipolysis and inhibits lipogenesis in adipose tissue without altering IGF-1 or blood glucose.",
    sources: [pubmed("21999160", "Stier et al. — Safety and efficacy of AOD-9604")],
  },
  {
    name: "Semaglutide",
    category: "Metabolic & GLP-1",
    researched: "Researched as a GLP-1 agonist for appetite regulation, glucose control, and fat loss.",
    molecularFormula: "C187H291N45O59",
    molecularWeight: "4113.6 g/mol",
    sequence: "GLP-1(7-37) analog with Aib8, Arg34 and C18 diacid at Lys26",
    compoundClass: "Long-acting GLP-1 receptor agonist",
    halfLife: "~7 days",
    target: "GLP-1 receptor",
    uses: ["Type 2 diabetes glycemic control", "Weight management", "Cardiovascular outcome research"],
    mechanism: "Activates GLP-1 receptors to enhance glucose-dependent insulin secretion, slow gastric emptying and reduce central appetite drive.",
    sources: [
      pubmed("33567185", "Wilding et al. — STEP 1 semaglutide weight trial"),
      pubmed("27633186", "Marso et al. — SUSTAIN-6 cardiovascular outcomes"),
    ],
  },
  {
    name: "Tirzepatide",
    category: "Metabolic & GLP-1",
    researched: "Researched as a dual GIP/GLP-1 agonist for weight management and metabolic health.",
    molecularFormula: "C225H348N48O68",
    molecularWeight: "4813.5 g/mol",
    sequence: "39-amino-acid GIP analog backbone with C20 fatty diacid",
    compoundClass: "Dual GIP/GLP-1 receptor agonist",
    halfLife: "~5 days",
    target: "GIP + GLP-1 receptors",
    uses: ["Weight reduction research", "Glycemic control", "Hepatic fat studies"],
    mechanism: "Co-activates GIP and GLP-1 receptors, producing greater insulinotropic and appetite-suppressing effects than GLP-1 agonism alone.",
    sources: [pubmed("35658024", "Jastreboff et al. — SURMOUNT-1 tirzepatide")],
  },
  {
    name: "Retatrutide",
    category: "Metabolic & GLP-1",
    researched: "Researched as a triple GIP/GLP-1/glucagon agonist for weight management and metabolic health.",
    molecularWeight: "~4731 g/mol",
    compoundClass: "Triple GIP/GLP-1/glucagon receptor agonist",
    halfLife: "~6 days",
    target: "GIP + GLP-1 + glucagon receptors",
    uses: ["Obesity research", "Hepatic steatosis models", "Energy-expenditure studies"],
    mechanism: "Adds glucagon-receptor agonism (raising energy expenditure) to incretin signaling, driving larger weight reductions in trials.",
    sources: [pubmed("37366315", "Jastreboff et al. — Retatrutide phase 2 obesity trial")],
  },
  {
    name: "Liraglutide",
    category: "Metabolic & GLP-1",
    researched: "Researched as a GLP-1 agonist for appetite control, glucose regulation, and fat loss.",
    molecularFormula: "C172H265N43O51",
    molecularWeight: "3751.2 g/mol",
    compoundClass: "GLP-1 receptor agonist (C16 acylated)",
    halfLife: "~13 hours",
    target: "GLP-1 receptor",
    uses: ["Daily glycemic control", "Weight management research"],
    mechanism: "Albumin-bound GLP-1 analog providing 24-hour receptor activation with daily administration.",
    sources: [pubmed("26132939", "Pi-Sunyer et al. — SCALE liraglutide trial")],
  },
  {
    name: "Dulaglutide",
    category: "Metabolic & GLP-1",
    researched: "Researched as a long-acting GLP-1 agonist for glycemic control and metabolic support.",
    molecularWeight: "~59,670 g/mol (Fc fusion)",
    compoundClass: "GLP-1 analog fused to IgG4 Fc",
    halfLife: "~5 days",
    target: "GLP-1 receptor",
    uses: ["Weekly glycemic control", "Cardiovascular risk research"],
    mechanism: "Fc fusion slows renal clearance, giving weekly dosing with sustained incretin signaling.",
  },
  {
    name: "MOTS-c",
    category: "Metabolic & GLP-1",
    researched: "Researched for mitochondrial function, insulin sensitivity, and metabolic efficiency.",
    molecularFormula: "C101H152N28O22S2",
    molecularWeight: "2174.6 g/mol",
    sequence: "Met-Arg-Trp-Gln-Glu-Met-Gly-Tyr-Ile-Phe-Tyr-Pro-Arg-Lys-Leu-Arg",
    compoundClass: "Mitochondrial-derived peptide",
    halfLife: "~30 minutes",
    target: "AMPK / folate-methionine cycle",
    uses: ["Insulin sensitivity research", "Exercise capacity and metabolic aging"],
    mechanism: "Translocates to the nucleus under metabolic stress and activates AMPK-dependent adaptive metabolic gene programs.",
    sources: [pubmed("25738459", "Lee et al. — MOTS-c regulates insulin sensitivity")],
  },
  {
    name: "5-Amino-1MQ",
    category: "Metabolic & GLP-1",
    researched: "Researched for NNMT inhibition, fat loss, and preservation of lean tissue.",
    molecularFormula: "C10H13N2+",
    molecularWeight: "173.2 g/mol",
    compoundClass: "Small-molecule NNMT inhibitor (not a peptide)",
    halfLife: "Several hours (oral)",
    target: "Nicotinamide N-methyltransferase (NNMT)",
    uses: ["Adipocyte metabolism research", "NAD+ salvage pathway studies"],
    mechanism: "Inhibits NNMT in adipocytes, raising cellular NAD+ and increasing energy expenditure in obesity models.",
    sources: [pubmed("30138619", "Neelakantan et al. — NNMT inhibitor 5-amino-1MQ")],
  },
  {
    name: "IGF-1 LR3",
    category: "Muscle & Anabolic",
    researched: "Researched for muscle cell growth, hypertrophy, and recovery signaling.",
    molecularFormula: "C400H625N111O115S9",
    molecularWeight: "9111.5 g/mol",
    compoundClass: "Long R3 analog of insulin-like growth factor 1",
    halfLife: "~20–30 hours",
    target: "IGF-1 receptor",
    uses: ["Hypertrophy and satellite-cell research", "Nutrient partitioning studies"],
    mechanism: "Reduced IGFBP binding extends half-life, prolonging PI3K/Akt/mTOR anabolic signaling in muscle tissue.",
  },
  {
    name: "IGF-1 DES",
    category: "Muscle & Anabolic",
    researched: "Researched for localized tissue growth, muscle repair, and anabolic signaling.",
    molecularWeight: "~7371 g/mol",
    compoundClass: "Truncated IGF-1 (des(1-3)) analog",
    halfLife: "~20–30 minutes",
    target: "IGF-1 receptor",
    uses: ["Localized tissue growth research", "Acute anabolic signaling"],
    mechanism: "Missing the first three N-terminal residues, it binds IGFBPs weakly and acts potently but briefly at the injection site.",
  },
  {
    name: "PEG-MGF",
    category: "Muscle & Anabolic",
    researched: "Researched for muscle stem cell activation, recovery, and tissue regeneration.",
    molecularWeight: "~2888 g/mol (peptide portion)",
    compoundClass: "Pegylated mechano growth factor (IGF-1Ec splice variant)",
    halfLife: "Extended vs. native MGF (pegylation)",
    target: "Satellite cells / muscle progenitor pool",
    uses: ["Muscle regeneration research", "Post-damage repair models"],
    mechanism: "Pegylation slows clearance of the MGF sequence, prolonging satellite-cell activation after mechanical overload.",
  },
  {
    name: "MGF",
    aka: "Mechano Growth Factor",
    category: "Muscle & Anabolic",
    researched: "Researched for muscle repair, hypertrophy, and training adaptation.",
    molecularWeight: "~2867 g/mol",
    compoundClass: "IGF-1 splice variant (IGF-1Ec) E-domain peptide",
    halfLife: "Minutes",
    target: "Muscle satellite cells",
    uses: ["Mechanical-overload adaptation research", "Local muscle repair"],
    mechanism: "Expressed after mechanical damage; drives satellite cell proliferation before differentiation into new myonuclei.",
  },
  {
    name: "Follistatin 344",
    category: "Muscle & Anabolic",
    researched: "Researched for myostatin inhibition, muscle growth, and tissue development.",
    molecularWeight: "~38,000 g/mol (protein)",
    compoundClass: "Myostatin/activin-binding glycoprotein",
    halfLife: "Short in circulation (minutes to hours)",
    target: "Myostatin (GDF-8) and activin A",
    uses: ["Muscle hypertrophy models", "Muscular dystrophy research"],
    mechanism: "Binds and neutralizes myostatin and activin, removing negative regulation of muscle fiber growth.",
    sources: [pubmed("19240031", "Kota et al. — Follistatin gene delivery and muscle mass")],
  },
  { name: "Follistatin 315", category: "Muscle & Anabolic", researched: "Researched for myostatin inhibition, muscle growth, and tissue development support.", compoundClass: "Circulating follistatin isoform", target: "Myostatin / activin", mechanism: "Longer circulating isoform with lower heparin-binding affinity than FS-344; studied for systemic myostatin neutralization." },
  { name: "ACE-031", category: "Muscle & Anabolic", researched: "Researched for myostatin pathway inhibition and muscle mass support.", compoundClass: "ActRIIB-Fc decoy receptor", halfLife: "~10–15 days", target: "Activin type IIB receptor ligands", mechanism: "Acts as a soluble decoy that sequesters myostatin and related ligands before they reach the ActRIIB receptor." },
  {
    name: "GHK-Cu",
    category: "Cosmetic & Sexual Health",
    researched: "Researched for skin regeneration, collagen synthesis, and hair follicle health.",
    molecularFormula: "C14H22N6O4Cu",
    molecularWeight: "403.9 g/mol",
    sequence: "Gly-His-Lys (copper-bound)",
    compoundClass: "Copper tripeptide complex",
    halfLife: "Short systemically; retained in dermal tissue",
    target: "Copper transport / collagen and gene expression",
    uses: ["Skin remodeling and anti-aging research", "Hair follicle studies", "Wound repair"],
    mechanism: "Delivers copper ions to tissue and modulates hundreds of genes tied to collagen synthesis, antioxidant defense and tissue remodeling.",
    sources: [pubmed("29144469", "Pickart & Margolina — GHK-Cu regenerative and protective actions")],
  },
  {
    name: "PT-141",
    aka: "Bremelanotide",
    category: "Cosmetic & Sexual Health",
    researched: "Researched for libido and sexual response via melanocortin receptor activation.",
    molecularFormula: "C50H68N14O10",
    molecularWeight: "1025.2 g/mol",
    sequence: "Ac-Nle-cyclo(Asp-His-D-Phe-Arg-Trp-Lys)-OH",
    compoundClass: "Cyclic melanocortin receptor agonist",
    halfLife: "~2.7 hours",
    target: "MC4R (central melanocortin receptor)",
    uses: ["Hypoactive sexual desire research", "Central arousal pathway studies"],
    mechanism: "Activates central MC4 receptors in the hypothalamus, increasing sexual desire through neural rather than vascular pathways.",
    sources: [pubmed("31356374", "Kingsberg et al. — Bremelanotide RECONNECT trials")],
  },
  { name: "Melanotan II", category: "Cosmetic & Sexual Health", researched: "Researched for melanogenesis, UV protection, and appetite suppression.", molecularFormula: "C50H69N15O9", molecularWeight: "1024.2 g/mol", sequence: "Ac-Nle-cyclo(Asp-His-D-Phe-Arg-Trp-Lys)-NH2", compoundClass: "Non-selective melanocortin agonist", halfLife: "~1–2 hours", target: "MC1R/MC3R/MC4R", uses: ["Melanogenesis research", "Appetite and libido pathways"], mechanism: "Broad melanocortin agonism stimulates melanin production (MC1R) plus appetite and libido effects (MC3R/MC4R)." },
  { name: "Melanotan I", aka: "Afamelanotide", category: "Cosmetic & Sexual Health", researched: "Researched for tanning response, melanogenesis, and UV protection.", molecularFormula: "C78H111N21O19", molecularWeight: "1646.8 g/mol", compoundClass: "Selective MC1R agonist", halfLife: "~1 hour (implant formulations longer)", target: "MC1R", uses: ["Photoprotection research", "Erythropoietic protoporphyria studies"], mechanism: "Selective MC1R activation increases eumelanin synthesis without significant MC4R appetite/libido effects." },
  {
    name: "Epithalon",
    category: "Longevity & Sleep",
    researched: "Researched for telomerase activation, sleep-cycle regulation, and longevity markers.",
    molecularFormula: "C14H22N4O9",
    molecularWeight: "390.3 g/mol",
    sequence: "Ala-Glu-Asp-Gly",
    compoundClass: "Synthetic pineal tetrapeptide",
    halfLife: "Minutes",
    target: "Telomerase / pineal melatonin regulation",
    uses: ["Telomere and cellular aging research", "Circadian and melatonin rhythm studies"],
    mechanism: "Reported to induce telomerase expression in somatic cells and normalize pineal melatonin rhythms in aging models.",
    sources: [pubmed("14523363", "Khavinson et al. — Epithalon and telomerase activity")],
  },
  {
    name: "DSIP",
    aka: "Delta Sleep-Inducing Peptide",
    category: "Longevity & Sleep",
    researched: "Researched for sleep architecture, stress recovery, and endocrine balance.",
    molecularFormula: "C35H48N10O15",
    molecularWeight: "848.8 g/mol",
    sequence: "Trp-Ala-Gly-Gly-Asp-Ala-Ser-Gly-Glu",
    compoundClass: "Nonapeptide neuromodulator",
    halfLife: "~7–15 minutes",
    target: "Delta-wave sleep and stress-axis modulation",
    uses: ["Slow-wave sleep research", "Stress and withdrawal models", "Chronic pain studies"],
    mechanism: "Modulates delta-wave activity and hypothalamic stress signaling; effects reported to persist beyond its short plasma half-life.",
    sources: [pubmed("6435948", "Graf & Kastin — DSIP: an update")],
  },
  { name: "Pinealon", category: "Longevity & Sleep", researched: "Researched for brain health, sleep regulation, and cellular differentiation.", sequence: "Glu-Asp-Arg", compoundClass: "Short peptide bioregulator", target: "Neuronal gene expression", mechanism: "Small peptide bioregulator reported to penetrate the nucleus and influence neuronal gene expression and oxidative stress resistance." },
  { name: "Thymalin", category: "Immune", researched: "Researched for immune modulation, thymus function, and overall immune balance.", compoundClass: "Thymus peptide extract complex", target: "T-cell maturation", uses: ["Immune restoration research", "Age-related immune decline"], mechanism: "Supports T-lymphocyte differentiation and rebalances immune cell populations in aging models." },
  {
    name: "Thymosin Alpha-1",
    category: "Immune",
    researched: "Researched for immune system modulation, antiviral response, and immune cell activity.",
    molecularFormula: "C129H215N33O55",
    molecularWeight: "3108.3 g/mol",
    sequence: "Ac-Ser-Asp-Ala-Ala-Val-Asp-Thr-Ser-Ser-Glu-Ile-Thr-Thr-Lys-Asp-Leu-Lys-Glu-Lys-Lys-Glu-Val-Val-Glu-Glu-Ala-Glu-Asn-OH",
    compoundClass: "28-amino-acid thymic peptide",
    halfLife: "~2 hours",
    target: "Toll-like receptors on dendritic cells / T cells",
    uses: ["Antiviral immune research", "Vaccine adjuvant studies", "Sepsis and immune-restoration models"],
    mechanism: "Promotes dendritic cell maturation and T-cell differentiation, strengthening cell-mediated immune responses.",
    sources: [pubmed("22405037", "Romani et al. — Thymosin alpha-1 immunomodulation")],
  },
  { name: "VIP", aka: "Vasoactive Intestinal Peptide", category: "Immune", researched: "Researched for immune regulation, gut health, and respiratory support.", molecularFormula: "C147H238N44O42S", molecularWeight: "3325.8 g/mol", compoundClass: "28-amino-acid neuropeptide", halfLife: "~1–2 minutes", target: "VPAC1 / VPAC2 receptors", uses: ["Chronic inflammatory response syndrome research", "Pulmonary hypertension studies"], mechanism: "Binds VPAC receptors to raise cAMP, producing vasodilation, bronchodilation and broad anti-inflammatory signaling." },
  {
    name: "Selank",
    category: "Cognitive & Neuro",
    researched: "Researched for anxiolytic effects, cognitive focus, and stress resilience.",
    molecularFormula: "C33H57N11O9",
    molecularWeight: "751.9 g/mol",
    sequence: "Thr-Lys-Pro-Arg-Pro-Gly-Pro",
    compoundClass: "Synthetic tuftsin analog",
    halfLife: "Minutes (peptide), effects longer",
    target: "GABAergic and monoamine systems, BDNF",
    uses: ["Generalized anxiety models", "Attention and memory research"],
    mechanism: "Modulates GABA-A expression and enkephalin degradation, producing anxiolysis without sedation or dependence in models.",
    sources: [pubmed("18683471", "Zozulya et al. — Selank in generalized anxiety")],
  },
  {
    name: "Semax",
    category: "Cognitive & Neuro",
    researched: "Researched for cognitive enhancement, neuroprotection, and BDNF expression.",
    molecularFormula: "C37H51N9O10S",
    molecularWeight: "813.9 g/mol",
    sequence: "Met-Glu-His-Phe-Pro-Gly-Pro",
    compoundClass: "ACTH(4-10) analog",
    halfLife: "Minutes (intranasal), prolonged CNS action",
    target: "BDNF/NGF expression, melanocortin pathway",
    uses: ["Stroke and ischemia recovery research", "Attention and memory studies"],
    mechanism: "Rapidly increases BDNF and NGF expression in the hippocampus without the hormonal effects of full-length ACTH.",
    sources: [pubmed("21689474", "Semax and BDNF expression research")],
  },
  { name: "Dihexa", category: "Cognitive & Neuro", researched: "Researched for cognitive support, neurogenesis, and improved synaptic connectivity.", molecularFormula: "C31H48N4O5", molecularWeight: "556.7 g/mol", compoundClass: "Angiotensin IV analog", halfLife: "Long (orally active, metabolically stable)", target: "HGF/c-Met signaling", uses: ["Synaptogenesis research", "Neurodegeneration models"], mechanism: "Potentiates hepatocyte growth factor signaling at the c-Met receptor, promoting dendritic spine formation." },
  { name: "Cerebrolysin", category: "Cognitive & Neuro", researched: "Researched for neuroprotection, recovery, and cognitive function support.", compoundClass: "Porcine brain-derived peptide preparation", target: "Neurotrophic factor pathways", uses: ["Stroke recovery research", "Traumatic brain injury and dementia models"], mechanism: "Mixture of low-molecular-weight neuropeptides with neurotrophic-factor-like activity on neuronal survival and plasticity." },
  { name: "Apamin", category: "Cognitive & Neuro", researched: "Researched for neuroprotection, cognitive enhancement, and calcium-activated potassium channel modulation.", molecularFormula: "C79H131N31O24S4", molecularWeight: "2027.3 g/mol", compoundClass: "Bee-venom-derived 18-residue neurotoxin peptide", target: "SK (small conductance Ca²⁺-activated K⁺) channels", mechanism: "Selective SK-channel blocker used as a pharmacological tool to study neuronal excitability and learning." },
  { name: "Oxytocin", category: "Hormonal", researched: "Researched for social bonding, stress response, and metabolic regulation.", molecularFormula: "C43H66N12O12S2", molecularWeight: "1007.2 g/mol", sequence: "Cys-Tyr-Ile-Gln-Asn-Cys-Pro-Leu-Gly-NH2 (disulfide bridge)", compoundClass: "Nonapeptide hormone", halfLife: "~3–5 minutes", target: "Oxytocin receptor", uses: ["Social cognition research", "Stress and anxiety models"], mechanism: "Activates oxytocin receptors in the amygdala and hypothalamus, modulating social salience and HPA-axis stress signaling." },
  { name: "Vasopressin", category: "Hormonal", researched: "Researched for memory consolidation, circadian rhythm, and water balance.", molecularFormula: "C46H65N15O12S2", molecularWeight: "1084.2 g/mol", compoundClass: "Nonapeptide hormone (ADH)", halfLife: "~10–20 minutes", target: "V1a / V1b / V2 receptors", mechanism: "Regulates renal water reabsorption (V2) and vascular tone plus CNS memory-related signaling (V1)." },
  { name: "Kisspeptin-10", category: "Hormonal", researched: "Researched for reproductive hormone signaling, LH/FSH release, and fertility.", molecularFormula: "C63H83N17O14", molecularWeight: "1302.4 g/mol", compoundClass: "KISS1 receptor agonist decapeptide", halfLife: "~4 minutes", target: "GPR54 (KISS1R)", uses: ["GnRH pulse and fertility research", "Hypothalamic-pituitary-gonadal axis studies"], mechanism: "Stimulates hypothalamic GnRH neurons upstream of LH and FSH release." },
  { name: "Triptorelin", category: "Hormonal", researched: "Researched for hormone modulation, testosterone regulation, and fertility contexts.", molecularFormula: "C64H82N18O13", molecularWeight: "1311.5 g/mol", compoundClass: "GnRH receptor agonist", halfLife: "~3 hours (depot forms far longer)", target: "GnRH receptor", mechanism: "Initial LH/FSH surge followed by receptor downregulation and suppression with continuous exposure." },
  { name: "hCG", aka: "Human Chorionic Gonadotropin", category: "Hormonal", researched: "Researched for fertility support, hormone preservation, and testicular function.", molecularWeight: "~36,700 g/mol (glycoprotein)", compoundClass: "LH-analog glycoprotein hormone", halfLife: "~24–36 hours", target: "LH/hCG receptor", uses: ["Testicular function preservation research", "Ovulation induction studies"], mechanism: "Mimics luteinizing hormone at the LH receptor, stimulating Leydig cell testosterone production." },
  { name: "Glutathione", category: "Other Research Compounds", researched: "Researched as a master antioxidant for oxidative stress, detoxification, and immune support.", molecularFormula: "C10H17N3O6S", molecularWeight: "307.3 g/mol", sequence: "gamma-Glu-Cys-Gly", compoundClass: "Endogenous tripeptide antioxidant", halfLife: "~10 minutes (IV)", target: "Reactive oxygen species / phase II detoxification", uses: ["Oxidative stress research", "Hepatic detoxification studies", "Skin pigmentation research"], mechanism: "Provides reducing equivalents via its cysteine thiol, neutralizing ROS and conjugating xenobiotics for elimination." },
  { name: "KLOW", category: "Other Research Compounds", researched: "Researched as a blended healing formulation (commonly GHK-Cu, KPV, BPC-157 and TB-500) for tissue repair and inflammation.", compoundClass: "Multi-peptide research blend", target: "Combined repair and anti-inflammatory pathways", mechanism: "Blends copper-tripeptide remodeling, KPV anti-inflammatory signaling, and BPC-157/TB-500 tissue-repair pathways in one preparation." },
  { name: "PNC-27", category: "Other Research Compounds", researched: "Researched for selective membrane-disrupting effects on damaged or transformed cells.", compoundClass: "p53-derived membrane-active peptide", target: "HDM-2 in cancer cell membranes", mechanism: "Binds membrane-bound HDM-2 expressed on transformed cells and forms pores, sparing normal cells in vitro." },
  { name: "S-23", category: "Other Research Compounds", researched: "Researched for selective androgen receptor modulation and body composition.", compoundClass: "SARM (non-peptide research chemical)", target: "Androgen receptor", mechanism: "High-affinity selective androgen receptor modulator studied in tissue-selectivity and male contraception models." },
  { name: "RAD-140", aka: "Testolone", category: "Other Research Compounds", researched: "Researched for neuroprotective and anabolic signaling properties.", compoundClass: "SARM (non-peptide research chemical)", target: "Androgen receptor", mechanism: "Non-steroidal AR agonist with tissue-selective anabolic signaling in preclinical models." },
  { name: "LGD-4033", aka: "Ligandrol", category: "Other Research Compounds", researched: "Researched for muscle preservation, strength, and lean tissue support.", compoundClass: "SARM (non-peptide research chemical)", target: "Androgen receptor", mechanism: "Selective AR binding studied for lean-mass preservation with reduced prostate activity relative to testosterone." },
  { name: "Albuterol", category: "Other Research Compounds", researched: "Researched for bronchodilation, fat oxidation, and metabolic performance.", molecularFormula: "C13H21NO3", molecularWeight: "239.3 g/mol", compoundClass: "Beta-2 adrenergic agonist (small molecule)", halfLife: "~4–6 hours", target: "Beta-2 adrenergic receptor", mechanism: "Beta-2 agonism relaxes bronchial smooth muscle and mildly increases lipolysis and metabolic rate." },
  { name: "Clenbuterol", category: "Other Research Compounds", researched: "Researched for beta-2 agonism, thermogenesis, and fat loss in animal models.", molecularFormula: "C12H18Cl2N2O", molecularWeight: "277.2 g/mol", compoundClass: "Long-acting beta-2 adrenergic agonist", halfLife: "~26–36 hours", target: "Beta-2 adrenergic receptor", mechanism: "Sustained beta-2 stimulation increases thermogenesis and lipolysis, with nutrient-repartitioning effects in livestock models." },
  { name: "T3", aka: "Liothyronine", category: "Other Research Compounds", researched: "Researched for thyroid hormone metabolism, energy expenditure, and fat oxidation.", molecularFormula: "C15H12I3NO4", molecularWeight: "650.97 g/mol", compoundClass: "Active thyroid hormone", halfLife: "~1 day", target: "Thyroid hormone receptors", mechanism: "Directly activates nuclear thyroid receptors, raising basal metabolic rate and substrate oxidation." },
  { name: "T4", aka: "Levothyroxine", category: "Other Research Compounds", researched: "Researched for thyroid replacement, metabolic rate, and hormone balance.", molecularFormula: "C15H11I4NO4", molecularWeight: "776.87 g/mol", compoundClass: "Prohormone thyroid hormone", halfLife: "~7 days", target: "Converted to T3 peripherally", mechanism: "Serves as a circulating reservoir converted by deiodinases into active T3 in peripheral tissues." },
];

export const PEPTIDE_GENERAL_SOURCES: PeptideSource[] = [
  { label: "PubMed — U.S. National Library of Medicine", url: "https://pubmed.ncbi.nlm.nih.gov/" },
  { label: "ClinicalTrials.gov", url: "https://clinicaltrials.gov/" },
  { label: "PubChem — Compound database", url: "https://pubchem.ncbi.nlm.nih.gov/" },
  { label: "DrugBank", url: "https://go.drugbank.com/" },
];
