export type PeptideSource = { label: string; url: string };

export const PEPTIDE_CATEGORIES = [
  "Healing & Recovery",
  "Growth Hormone",
  "Metabolic",
  "Cognitive",
  "Longevity",
  "Cosmetic & Wellness",
  "Blends",
  "Supplies",
] as const;

export type PeptideCategory = (typeof PEPTIDE_CATEGORIES)[number];

export type PeptideEntry = {
  name: string;
  aka?: string;
  category: PeptideCategory;
  researched: string;
  /** Molecular profile */
  compoundClass?: string;
  molecularFormula?: string;
  molecularWeight?: string;
  sequence?: string;
  /** For blends — what's actually in the vial */
  contains?: string[];
  target?: string;
  halfLife?: string;
  uses?: string[];
  mechanism?: string;
  sources?: PeptideSource[];
};

const pubmed = (id: string, label: string): PeptideSource => ({
  label,
  url: `https://pubmed.ncbi.nlm.nih.gov/${id}/`,
});

export const PEPTIDE_LIBRARY: PeptideEntry[] = [
  {
    name: "TB-500",
    aka: "Thymosin Beta-4 fragment",
    category: "Healing & Recovery",
    researched: "Studied for soft-tissue recovery, muscle and tendon repair, and cell migration.",
    compoundClass: "Synthetic fragment of the actin-binding protein Thymosin Beta-4",
    molecularFormula: "C33H55N9O12",
    molecularWeight: "889.0 g/mol",
    sequence: "Ac-Leu-Lys-Lys-Thr-Glu-Thr-Gln",
    target: "G-actin / actin cytoskeleton",
    halfLife: "~2–3 hours",
    uses: ["Muscle and tendon repair models", "Cardiac and corneal tissue repair", "Angiogenesis and cell migration"],
    mechanism:
      "Binds G-actin and regulates actin polymerization, enabling cell migration, endothelial differentiation and new vessel formation in injured tissue.",
    sources: [
      pubmed("22348196", "Goldstein & Kleinman — Thymosin β4 in tissue repair"),
      pubmed("20955691", "Crockford et al. — Thymosin β4 clinical potential"),
    ],
  },
  {
    name: "BPC-157",
    aka: "Body Protection Compound 157",
    category: "Healing & Recovery",
    researched: "Studied for gut lining repair, tendon and ligament healing, and anti-inflammatory signaling.",
    compoundClass: "Synthetic pentadecapeptide from human gastric juice protein BPC",
    molecularFormula: "C62H98N16O22",
    molecularWeight: "1419.5 g/mol",
    sequence: "Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val",
    target: "VEGFR2 / nitric oxide signaling",
    halfLife: "~4 hours (subcutaneous, animal models)",
    uses: ["Tendon, ligament and muscle injury models", "GI mucosal integrity and ulcer models", "Angiogenesis and wound closure"],
    mechanism:
      "Upregulates VEGFR2 and the nitric oxide system, promoting angiogenesis and fibroblast migration at injury sites while modulating inflammatory cytokines.",
    sources: [
      pubmed("29863456", "Chang et al. — BPC-157 and tendon fibroblast outgrowth"),
      pubmed("30915550", "Sikiric et al. — Stable gastric pentadecapeptide BPC-157"),
    ],
  },
  {
    name: "Semax",
    category: "Cognitive",
    researched: "Studied for cognitive performance, neuroprotection, and BDNF expression.",
    compoundClass: "ACTH(4-10) analog",
    molecularFormula: "C37H51N9O10S",
    molecularWeight: "813.9 g/mol",
    sequence: "Met-Glu-His-Phe-Pro-Gly-Pro",
    target: "BDNF / NGF expression, melanocortin pathway",
    halfLife: "Minutes in plasma; prolonged CNS action",
    uses: ["Stroke and ischemia recovery research", "Attention, memory and focus studies", "Neuroprotection models"],
    mechanism: "Rapidly increases BDNF and NGF expression in the hippocampus without the hormonal effects of full-length ACTH.",
    sources: [pubmed("21689474", "Semax and hippocampal BDNF expression")],
  },
  {
    name: "Bacteriostatic Water",
    aka: "0.9% benzyl alcohol sterile water",
    category: "Supplies",
    researched: "The diluent used to reconstitute lyophilized research peptides.",
    compoundClass: "Sterile water with 0.9% benzyl alcohol preservative",
    molecularFormula: "H2O + C7H8O (benzyl alcohol)",
    target: "Reconstitution solvent",
    halfLife: "~28 days once punctured, refrigerated",
    uses: ["Reconstituting lyophilized peptide powder", "Multi-dose vial preparation"],
    mechanism:
      "Benzyl alcohol inhibits bacterial growth, allowing a reconstituted vial to be accessed multiple times over roughly 28 days when refrigerated.",
  },
  {
    name: "GLOW",
    category: "Blends",
    researched: "A repair and skin-quality blend studied for tissue healing, collagen synthesis, and recovery.",
    compoundClass: "Multi-peptide research blend",
    contains: ["GHK-Cu — copper tripeptide", "BPC-157 — pentadecapeptide", "TB-500 — Thymosin Beta-4 fragment"],
    target: "Collagen remodeling + angiogenesis + actin-driven cell migration",
    uses: ["Skin quality and collagen research", "Systemic soft-tissue repair", "Post-injury recovery models"],
    mechanism:
      "Pairs GHK-Cu's copper-driven collagen and remodeling signaling with the angiogenic (BPC-157) and cell-migration (TB-500) repair pathways in one preparation.",
    sources: [pubmed("29144469", "Pickart & Margolina — GHK-Cu regenerative actions")],
  },
  {
    name: "IGF-1 LR3",
    category: "Growth Hormone",
    researched: "Studied for muscle cell growth, hypertrophy, and recovery signaling.",
    compoundClass: "Long R3 analog of insulin-like growth factor 1",
    molecularFormula: "C400H625N111O115S9",
    molecularWeight: "9111.5 g/mol",
    target: "IGF-1 receptor",
    halfLife: "~20–30 hours",
    uses: ["Hypertrophy and satellite-cell research", "Nutrient partitioning studies"],
    mechanism: "Reduced IGFBP binding extends half-life, prolonging PI3K/Akt/mTOR anabolic signaling in muscle tissue.",
  },
  {
    name: "MOTS-c",
    category: "Longevity",
    researched: "Studied for mitochondrial function, insulin sensitivity, and metabolic efficiency.",
    compoundClass: "Mitochondrial-derived peptide",
    molecularFormula: "C101H152N28O22S2",
    molecularWeight: "2174.6 g/mol",
    sequence: "Met-Arg-Trp-Gln-Glu-Met-Gly-Tyr-Ile-Phe-Tyr-Pro-Arg-Lys-Leu-Arg",
    target: "AMPK / folate-methionine cycle",
    halfLife: "~30 minutes",
    uses: ["Insulin sensitivity research", "Exercise capacity studies", "Metabolic aging models"],
    mechanism: "Translocates to the nucleus under metabolic stress and activates AMPK-dependent adaptive metabolic gene programs.",
    sources: [pubmed("25738459", "Lee et al. — MOTS-c regulates insulin sensitivity")],
  },
  {
    name: "AHK-Cu",
    category: "Cosmetic & Wellness",
    researched: "Studied for hair follicle support, dermal microcirculation, and collagen production.",
    compoundClass: "Copper tripeptide complex",
    molecularFormula: "C16H25N7O4Cu",
    molecularWeight: "~403 g/mol (copper complex)",
    sequence: "Ala-His-Lys (copper-bound)",
    target: "VEGF expression / dermal papilla cells",
    uses: ["Hair growth and follicle research", "Skin firmness and vascularization studies"],
    mechanism: "Delivers copper to dermal tissue and upregulates VEGF, increasing follicular blood supply and collagen production in models.",
  },
  {
    name: "GLP2-TZ",
    aka: "Dual GIP/GLP-1 research analog",
    category: "Metabolic",
    researched: "Studied as a dual GIP/GLP-1 agonist for weight management, appetite control, and glycemic regulation.",
    compoundClass: "Dual incretin receptor agonist (tirzepatide-class)",
    molecularFormula: "C225H348N48O68",
    molecularWeight: "4813.5 g/mol",
    target: "GIP + GLP-1 receptors",
    halfLife: "~5 days",
    uses: ["Weight reduction research", "Glycemic control", "Hepatic fat studies"],
    mechanism: "Co-activates GIP and GLP-1 receptors, producing greater insulinotropic and appetite-suppressing effects than GLP-1 agonism alone.",
    sources: [pubmed("35658024", "Jastreboff et al. — SURMOUNT-1 dual agonist trial")],
  },
  {
    name: "NAD+",
    aka: "Nicotinamide adenine dinucleotide",
    category: "Longevity",
    researched: "Studied for cellular energy metabolism, DNA repair, and sirtuin activity.",
    compoundClass: "Endogenous redox coenzyme (not a peptide)",
    molecularFormula: "C21H27N7O14P2",
    molecularWeight: "663.4 g/mol",
    target: "Sirtuins, PARPs, mitochondrial electron transport",
    halfLife: "Rapid clearance; tissue NAD+ turnover in hours",
    uses: ["Mitochondrial function research", "DNA repair and cellular aging", "Cognitive and energy studies"],
    mechanism: "Serves as the electron carrier for oxidative metabolism and the required substrate for sirtuin and PARP-mediated DNA repair.",
    sources: [pubmed("29883761", "Rajman et al. — NAD+ boosting molecules review")],
  },
  {
    name: "Kisspeptin",
    aka: "Kisspeptin-10",
    category: "Metabolic",
    researched: "Studied for reproductive hormone signaling, LH/FSH release, and fertility.",
    compoundClass: "KISS1 receptor agonist decapeptide",
    molecularFormula: "C63H83N17O14",
    molecularWeight: "1302.4 g/mol",
    target: "GPR54 (KISS1R)",
    halfLife: "~4 minutes",
    uses: ["GnRH pulse and fertility research", "HPG axis studies", "Libido research"],
    mechanism: "Stimulates hypothalamic GnRH neurons upstream of LH and FSH release.",
    sources: [pubmed("21084400", "Jayasena et al. — Kisspeptin and gonadotropin release")],
  },
  {
    name: "CJC-1295 No DAC + Ipamorelin",
    category: "Blends",
    researched: "Studied as a synergistic GH pulse blend for recovery, sleep, and body composition.",
    compoundClass: "GHRH analog + selective ghrelin-receptor agonist",
    contains: ["CJC-1295 without DAC (Mod GRF 1-29) — GHRH analog", "Ipamorelin — selective GHS-R1a agonist"],
    target: "GHRH receptor + GHS-R1a",
    halfLife: "~30 min (Mod GRF) / ~2 hours (Ipamorelin)",
    uses: ["Pulsatile GH release research", "Recovery and sleep studies", "Lean mass and body composition"],
    mechanism:
      "The GHRH analog raises the GH pulse baseline while the ghrelin-receptor agonist raises pulse amplitude, producing a larger, more physiologic release than either alone.",
    sources: [pubmed("9849822", "Raun et al. — Ipamorelin selective GH secretagogue")],
  },
  {
    name: "Tesamorelin",
    category: "Growth Hormone",
    researched: "Studied for reducing visceral adipose tissue and improving lipid metabolism.",
    compoundClass: "Stabilized GHRH(1-44) analog",
    molecularFormula: "C221H366N72O67S",
    molecularWeight: "5135.9 g/mol",
    sequence: "trans-3-hexenoyl-GHRH(1-44) amide",
    target: "GHRH receptor",
    halfLife: "~26–38 minutes",
    uses: ["Visceral adipose tissue reduction", "Liver fat and triglyceride studies", "Cognition in aging research"],
    mechanism: "Extended-stability GHRH analog that increases endogenous GH and IGF-1, preferentially mobilizing visceral fat stores.",
    sources: [pubmed("21030489", "Falutz et al. — Tesamorelin and visceral fat")],
  },
  {
    name: "Wolverine",
    category: "Blends",
    researched: "A dedicated repair blend studied for injury recovery, connective tissue healing, and inflammation.",
    compoundClass: "Multi-peptide research blend",
    contains: ["BPC-157 — pentadecapeptide", "TB-500 — Thymosin Beta-4 fragment"],
    target: "VEGFR2 angiogenesis + actin-mediated cell migration",
    uses: ["Tendon, ligament and joint repair models", "Post-surgical recovery research", "Gut and systemic inflammation"],
    mechanism:
      "Combines BPC-157's angiogenic, growth-factor-driven healing with TB-500's actin-regulated cell migration to cover both blood supply and cell recruitment in tissue repair.",
  },
  {
    name: "PT-141",
    aka: "Bremelanotide",
    category: "Cosmetic & Wellness",
    researched: "Studied for libido and sexual response via central melanocortin activation.",
    compoundClass: "Cyclic melanocortin receptor agonist",
    molecularFormula: "C50H68N14O10",
    molecularWeight: "1025.2 g/mol",
    sequence: "Ac-Nle-cyclo(Asp-His-D-Phe-Arg-Trp-Lys)-OH",
    target: "MC4R (central melanocortin receptor)",
    halfLife: "~2.7 hours",
    uses: ["Hypoactive sexual desire research", "Central arousal pathway studies"],
    mechanism: "Activates central MC4 receptors in the hypothalamus, increasing desire through neural rather than vascular pathways.",
    sources: [pubmed("31356374", "Kingsberg et al. — Bremelanotide RECONNECT trials")],
  },
  {
    name: "Cagrilintide",
    category: "Metabolic",
    researched: "Studied as a long-acting amylin analog for satiety, gastric emptying, and weight management.",
    compoundClass: "Acylated amylin (IAPP) analog",
    molecularWeight: "~3751 g/mol",
    target: "Amylin and calcitonin receptors",
    halfLife: "~7–8 days",
    uses: ["Appetite and satiety research", "Weight management combination studies with GLP-1 agonists"],
    mechanism: "Activates amylin/calcitonin receptors in the area postrema, slowing gastric emptying and prolonging satiety signaling.",
    sources: [pubmed("34186022", "Lau et al. — Cagrilintide phase 2 obesity trial")],
  },
  {
    name: "KPV",
    category: "Healing & Recovery",
    researched: "Studied for anti-inflammatory effects, skin healing, and immune modulation.",
    compoundClass: "C-terminal tripeptide of alpha-MSH",
    molecularFormula: "C19H26N6O4",
    molecularWeight: "402.4 g/mol",
    sequence: "Lys-Pro-Val",
    target: "NF-κB signaling / melanocortin pathway",
    halfLife: "Short (minutes to ~1 hour)",
    uses: ["Colitis and IBD models", "Dermatitis and skin repair", "Cytokine research"],
    mechanism: "Suppresses NF-κB and pro-inflammatory cytokine transcription without the pigmentation effects of full-length alpha-MSH.",
    sources: [pubmed("18845615", "Dalmasso et al. — KPV and intestinal inflammation")],
  },
  {
    name: "Adamax",
    category: "Cognitive",
    researched: "A nootropic blend studied for memory, focus, and synaptic plasticity.",
    compoundClass: "Multi-peptide cognitive research blend",
    contains: ["N-Acetyl Semax Amidate — ACTH(4-10) analog", "Dihexa — angiotensin IV analog"],
    target: "BDNF/NGF expression + HGF/c-Met synaptogenesis",
    uses: ["Memory and learning research", "Neuroplasticity studies", "Neurodegeneration models"],
    mechanism:
      "Pairs Semax-driven BDNF/NGF upregulation with Dihexa's potentiation of hepatocyte growth factor signaling at c-Met, which promotes dendritic spine formation.",
  },
  {
    name: "Ipamorelin",
    category: "Growth Hormone",
    researched: "Studied as a selective GH secretagogue that raises GH without spiking cortisol or prolactin.",
    compoundClass: "Pentapeptide ghrelin-receptor (GHS-R1a) agonist",
    molecularFormula: "C38H49N9O5",
    molecularWeight: "711.9 g/mol",
    sequence: "Aib-His-D-2-Nal-D-Phe-Lys-NH2",
    target: "GHS-R1a (ghrelin receptor)",
    halfLife: "~2 hours",
    uses: ["Selective GH pulse research", "Recovery and lean-mass studies", "Gastric motility research"],
    mechanism: "Selectively activates the ghrelin receptor to trigger GH release with minimal effect on ACTH, cortisol or prolactin.",
    sources: [pubmed("9849822", "Raun et al. — Ipamorelin, the first selective GH secretagogue")],
  },
  {
    name: "Melanotan II",
    aka: "MT-2",
    category: "Cosmetic & Wellness",
    researched: "Studied for melanogenesis, UV protection, appetite, and libido pathways.",
    compoundClass: "Non-selective melanocortin agonist",
    molecularFormula: "C50H69N15O9",
    molecularWeight: "1024.2 g/mol",
    sequence: "Ac-Nle-cyclo(Asp-His-D-Phe-Arg-Trp-Lys)-NH2",
    target: "MC1R / MC3R / MC4R",
    halfLife: "~1–2 hours",
    uses: ["Melanogenesis research", "Appetite and libido pathway studies"],
    mechanism: "Broad melanocortin agonism stimulates melanin production (MC1R) alongside appetite and libido effects (MC3R/MC4R).",
  },
  {
    name: "Melanotan I",
    aka: "MT-1 / Afamelanotide",
    category: "Cosmetic & Wellness",
    researched: "Studied for tanning response, melanogenesis, and photoprotection.",
    compoundClass: "Selective MC1R agonist",
    molecularFormula: "C78H111N21O19",
    molecularWeight: "1646.8 g/mol",
    target: "MC1R",
    halfLife: "~1 hour (implant formulations longer)",
    uses: ["Photoprotection research", "Erythropoietic protoporphyria studies"],
    mechanism: "Selective MC1R activation increases eumelanin synthesis without the MC4R appetite and libido effects of MT-2.",
    sources: [pubmed("26026583", "Langendonk et al. — Afamelanotide for EPP")],
  },
  {
    name: "SS-31",
    aka: "Elamipretide",
    category: "Longevity",
    researched: "Studied for mitochondrial function, cardiolipin protection, and cellular energy output.",
    compoundClass: "Mitochondria-targeted tetrapeptide",
    molecularFormula: "C32H49N9O5",
    molecularWeight: "639.8 g/mol",
    sequence: "D-Arg-Dmt-Lys-Phe-NH2",
    target: "Cardiolipin on the inner mitochondrial membrane",
    halfLife: "~2–4 hours",
    uses: ["Mitochondrial myopathy research", "Cardiac and renal ischemia models", "Age-related muscle function"],
    mechanism: "Binds cardiolipin to stabilize cristae architecture, improving electron transport efficiency and reducing reactive oxygen species leak.",
    sources: [pubmed("28158588", "Szeto — Elamipretide and cardiolipin")],
  },
  {
    name: "Glutathione",
    category: "Longevity",
    researched: "Studied as the body's master antioxidant for oxidative stress, detoxification, and immune support.",
    compoundClass: "Endogenous tripeptide antioxidant",
    molecularFormula: "C10H17N3O6S",
    molecularWeight: "307.3 g/mol",
    sequence: "gamma-Glu-Cys-Gly",
    target: "Reactive oxygen species / phase II detoxification",
    halfLife: "~10 minutes (IV)",
    uses: ["Oxidative stress research", "Hepatic detoxification studies", "Skin pigmentation research"],
    mechanism: "Provides reducing equivalents through its cysteine thiol, neutralizing ROS and conjugating xenobiotics for elimination.",
  },
  {
    name: "KLOW",
    category: "Blends",
    researched: "A four-compound repair blend studied for tissue healing, inflammation, and skin quality.",
    compoundClass: "Multi-peptide research blend",
    contains: ["GHK-Cu — copper tripeptide", "KPV — anti-inflammatory tripeptide", "BPC-157 — pentadecapeptide", "TB-500 — Thymosin Beta-4 fragment"],
    target: "Collagen remodeling + NF-κB suppression + angiogenesis + cell migration",
    uses: ["Comprehensive tissue repair research", "Inflammatory injury models", "Skin and connective tissue studies"],
    mechanism:
      "Layers copper-tripeptide remodeling, KPV's NF-κB suppression, and the BPC-157/TB-500 repair axis so vascular, inflammatory and structural pathways are addressed together.",
  },
  {
    name: "CJC-1295 w/ DAC",
    category: "Growth Hormone",
    researched: "Studied as a long-acting GHRH analog that elevates baseline growth hormone and IGF-1.",
    compoundClass: "GHRH(1-29) analog with Drug Affinity Complex",
    molecularFormula: "C165H269N47O46",
    molecularWeight: "3647.2 g/mol",
    sequence: "Tyr-D-Ala-Asp-Ala-Ile-Phe-Thr-Gln-Ser-Tyr-Arg-Lys-Val-Leu-Ala-Gln-Leu-Ser-Ala-Arg-Lys-Leu-Leu-Gln-Asp-Ile-Leu-Ser-Arg-(Lys-DAC)",
    target: "GHRH receptor (pituitary somatotrophs)",
    halfLife: "~6–8 days",
    uses: ["Sustained GH/IGF-1 elevation studies", "Body composition research", "Sleep and recovery research"],
    mechanism: "Binds albumin through its DAC linker for extended circulation, giving continuous GHRH-receptor stimulation and a raised GH baseline.",
    sources: [pubmed("16352683", "Teichman et al. — CJC-1295 sustained GH/IGF-1 elevation")],
  },
  {
    name: "GLP3-RT",
    aka: "Triple agonist research analog",
    category: "Metabolic",
    researched: "Studied as a triple GIP/GLP-1/glucagon agonist for weight management and metabolic health.",
    compoundClass: "Triple incretin/glucagon receptor agonist (retatrutide-class)",
    molecularWeight: "~4731 g/mol",
    target: "GIP + GLP-1 + glucagon receptors",
    halfLife: "~6 days",
    uses: ["Obesity research", "Hepatic steatosis models", "Energy expenditure studies"],
    mechanism: "Adds glucagon-receptor agonism, which raises energy expenditure, on top of dual incretin signaling for larger weight reductions in trials.",
    sources: [pubmed("37366315", "Jastreboff et al. — Triple agonist phase 2 obesity trial")],
  },
  {
    name: "GHK-Cu",
    category: "Cosmetic & Wellness",
    researched: "Studied for skin regeneration, collagen synthesis, and hair follicle health.",
    compoundClass: "Copper tripeptide complex",
    molecularFormula: "C14H22N6O4Cu",
    molecularWeight: "403.9 g/mol",
    sequence: "Gly-His-Lys (copper-bound)",
    target: "Copper transport / collagen and remodeling gene expression",
    halfLife: "Short systemically; retained in dermal tissue",
    uses: ["Skin remodeling and anti-aging research", "Hair follicle studies", "Wound repair"],
    mechanism: "Delivers copper ions to tissue and modulates hundreds of genes tied to collagen synthesis, antioxidant defense and tissue remodeling.",
    sources: [pubmed("29144469", "Pickart & Margolina — GHK-Cu regenerative and protective actions")],
  },
  {
    name: "Selank",
    category: "Cognitive",
    researched: "Studied for anxiolytic effects, cognitive focus, and stress resilience.",
    compoundClass: "Synthetic tuftsin analog",
    molecularFormula: "C33H57N11O9",
    molecularWeight: "751.9 g/mol",
    sequence: "Thr-Lys-Pro-Arg-Pro-Gly-Pro",
    target: "GABAergic and monoamine systems, BDNF",
    halfLife: "Minutes in plasma; effects outlast clearance",
    uses: ["Generalized anxiety models", "Attention and memory research", "Stress adaptation studies"],
    mechanism: "Modulates GABA-A expression and slows enkephalin degradation, producing anxiolysis without sedation or dependence in models.",
    sources: [pubmed("18683471", "Zozulya et al. — Selank in generalized anxiety")],
  },
];

export const PEPTIDE_GENERAL_SOURCES: PeptideSource[] = [
  { label: "PubMed — U.S. National Library of Medicine", url: "https://pubmed.ncbi.nlm.nih.gov/" },
  { label: "ClinicalTrials.gov", url: "https://clinicaltrials.gov/" },
  { label: "PubChem — Compound database", url: "https://pubchem.ncbi.nlm.nih.gov/" },
  { label: "DrugBank", url: "https://go.drugbank.com/" },
];
